"""add resolved index to annotations

Revision ID: 1a4b30fac2d0
Revises: a3f8e1b2c4d6
Create Date: 2026-04-12 19:16:40.151575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a4b30fac2d0'
down_revision: Union[str, None] = 'a3f8e1b2c4d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_annotations_resolved', 'annotations', ['resolved'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_annotations_resolved', table_name='annotations')
    # ### end Alembic commands ###
