"""add sandbox_url column

Revision ID: 709acffa524d
Revises: 1a4b30fac2d0
Create Date: 2026-04-12 23:46:05.985156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '709acffa524d'
down_revision: Union[str, None] = '1a4b30fac2d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sandboxes', sa.Column('sandbox_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sandboxes', 'sandbox_url')
    # ### end Alembic commands ###
