"""initial schema

Revision ID: 72589ef730ee
Revises: 
Create Date: 2026-04-11 16:57:29.521847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72589ef730ee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('onboarded', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('plan', sa.String(), server_default='free', nullable=False),
    sa.Column('token_limit', sa.Integer(), server_default='10000', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ai_providers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider_name', sa.Enum('anthropic', 'openai', 'gemini', 'grok', 'mistral', 'cohere', 'deepseek', 'together', name='providername'), nullable=False),
    sa.Column('encrypted_key', sa.LargeBinary(), nullable=False),
    sa.Column('key_iv', sa.LargeBinary(), nullable=False),
    sa.Column('key_tag', sa.LargeBinary(), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_connected', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_providers_user_id', 'ai_providers', ['user_id'], unique=False)
    op.create_index('ix_ai_providers_user_id_status', 'ai_providers', ['user_id', 'status'], unique=False)
    op.create_index('uq_ai_providers_user_provider', 'ai_providers', ['user_id', 'provider_name'], unique=True)
    op.create_table('idea_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('questionnaire_answers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_idea_sessions_user_id', 'idea_sessions', ['user_id'], unique=False)
    op.create_index('ix_idea_sessions_user_id_status', 'idea_sessions', ['user_id', 'status'], unique=False)
    op.create_table('projects',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'building', 'live', 'error', 'archived', name='projectstatus'), server_default='draft', nullable=False),
    sa.Column('framework', sa.Enum('nextjs', 'vite_react', 'fastapi', 'django', 'express', name='framework'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_user_id', 'projects', ['user_id'], unique=False)
    op.create_index('ix_projects_user_id_status', 'projects', ['user_id', 'status'], unique=False)
    op.create_index('ix_projects_user_id_status_updated', 'projects', ['user_id', 'status', 'updated_at'], unique=False)
    op.create_table('ideas',
    sa.Column('idea_session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tech_stack', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('market_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('saved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['idea_session_id'], ['idea_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ideas_idea_session_id', 'ideas', ['idea_session_id'], unique=False)
    op.create_index('ix_ideas_user_id', 'ideas', ['user_id'], unique=False)
    op.create_index('ix_ideas_user_id_status', 'ideas', ['user_id', 'status'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='pipelinestatus'), server_default='pending', nullable=False),
    sa.Column('current_stage', sa.Integer(), server_default='1', nullable=False),
    sa.Column('idea_spec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pipeline_runs_project_id', 'pipeline_runs', ['project_id'], unique=False)
    op.create_index('ix_pipeline_runs_user_id', 'pipeline_runs', ['user_id'], unique=False)
    op.create_index('ix_pipeline_runs_user_id_status', 'pipeline_runs', ['user_id', 'status'], unique=False)
    op.create_table('sandboxes',
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('warm', 'claimed', 'building', 'stopping', 'stopped', 'error', name='sandboxstatus'), server_default='warm', nullable=False),
    sa.Column('northflank_service_id', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sandboxes_project_id', 'sandboxes', ['project_id'], unique=False)
    op.create_index('ix_sandboxes_status', 'sandboxes', ['status'], unique=False)
    op.create_table('agent_outputs',
    sa.Column('pipeline_run_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gate_passed', sa.Boolean(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_outputs_pipeline_run_id', 'agent_outputs', ['pipeline_run_id'], unique=False)
    op.create_table('builds',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('pipeline_run_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'building', 'success', 'failed', name='buildstatus'), server_default='pending', nullable=False),
    sa.Column('gate_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_files_key', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_builds_pipeline_run_id', 'builds', ['pipeline_run_id'], unique=False)
    op.create_index('ix_builds_project_id', 'builds', ['project_id'], unique=False)
    op.create_index('ix_builds_project_id_status', 'builds', ['project_id', 'status'], unique=False)
    op.create_index('ix_builds_user_id', 'builds', ['user_id'], unique=False)
    op.create_index('ix_builds_user_id_status', 'builds', ['user_id', 'status'], unique=False)
    op.create_table('editor_sessions',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sandbox_id', sa.UUID(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sandbox_id'], ['sandboxes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_editor_sessions_project_id', 'editor_sessions', ['project_id'], unique=False)
    op.create_index('ix_editor_sessions_sandbox_id', 'editor_sessions', ['sandbox_id'], unique=False)
    op.create_index('ix_editor_sessions_user_id', 'editor_sessions', ['user_id'], unique=False)
    op.create_index('ix_editor_sessions_user_id_status', 'editor_sessions', ['user_id', 'status'], unique=False)
    op.create_table('preview_shares',
    sa.Column('sandbox_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sandbox_id'], ['sandboxes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('ix_preview_shares_sandbox_id', 'preview_shares', ['sandbox_id'], unique=False)
    op.create_index('ix_preview_shares_user_id', 'preview_shares', ['user_id'], unique=False)
    op.create_index('ix_preview_shares_user_id_status', 'preview_shares', ['user_id', 'status'], unique=False)
    op.create_table('accessibility_reports',
    sa.Column('build_id', sa.UUID(), nullable=False),
    sa.Column('route', sa.String(), nullable=False),
    sa.Column('critical_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('serious_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('violations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_accessibility_reports_build_id', 'accessibility_reports', ['build_id'], unique=False)
    op.create_table('annotations',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('editor_session_id', sa.UUID(), nullable=True),
    sa.Column('css_selector', sa.String(), nullable=False),
    sa.Column('route', sa.String(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('x_pct', sa.Float(), nullable=False),
    sa.Column('y_pct', sa.Float(), nullable=False),
    sa.Column('resolved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['editor_session_id'], ['editor_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_annotations_editor_session_id', 'annotations', ['editor_session_id'], unique=False)
    op.create_index('ix_annotations_project_id', 'annotations', ['project_id'], unique=False)
    op.create_index('ix_annotations_user_id', 'annotations', ['user_id'], unique=False)
    op.create_index('ix_annotations_user_id_status', 'annotations', ['user_id', 'status'], unique=False)
    op.create_table('build_snapshots',
    sa.Column('build_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('agent_number', sa.Integer(), nullable=False),
    sa.Column('agent_type', sa.String(), nullable=False),
    sa.Column('screenshot_url', sa.String(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_build_snapshots_build_id', 'build_snapshots', ['build_id'], unique=False)
    op.create_index('ix_build_snapshots_project_id', 'build_snapshots', ['project_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='chatrole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='sent', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['editor_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_messages_project_id', 'chat_messages', ['project_id'], unique=False)
    op.create_index('ix_chat_messages_session_id', 'chat_messages', ['session_id'], unique=False)
    op.create_index('ix_chat_messages_user_id', 'chat_messages', ['user_id'], unique=False)
    op.create_index('ix_chat_messages_user_id_status', 'chat_messages', ['user_id', 'status'], unique=False)
    op.create_table('coherence_reports',
    sa.Column('build_id', sa.UUID(), nullable=False),
    sa.Column('critical_errors', sa.Integer(), server_default='0', nullable=False),
    sa.Column('auto_fixes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('report_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_coherence_reports_build_id', 'coherence_reports', ['build_id'], unique=False)
    op.create_table('deployments',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('build_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deployments_build_id', 'deployments', ['build_id'], unique=False)
    op.create_index('ix_deployments_project_id', 'deployments', ['project_id'], unique=False)
    op.create_index('ix_deployments_user_id', 'deployments', ['user_id'], unique=False)
    op.create_index('ix_deployments_user_id_status', 'deployments', ['user_id', 'status'], unique=False)
    op.create_table('hot_fix_records',
    sa.Column('build_id', sa.UUID(), nullable=False),
    sa.Column('failed_gate', sa.String(), nullable=False),
    sa.Column('failing_file', sa.String(), nullable=False),
    sa.Column('fix_applied', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hot_fix_records_build_id', 'hot_fix_records', ['build_id'], unique=False)
    op.create_table('performance_reports',
    sa.Column('build_id', sa.UUID(), nullable=False),
    sa.Column('route', sa.String(), nullable=False),
    sa.Column('lcp_ms', sa.Float(), nullable=True),
    sa.Column('cls', sa.Float(), nullable=True),
    sa.Column('fid_ms', sa.Float(), nullable=True),
    sa.Column('bundle_kb', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_performance_reports_build_id', 'performance_reports', ['build_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_performance_reports_build_id', table_name='performance_reports')
    op.drop_table('performance_reports')
    op.drop_index('ix_hot_fix_records_build_id', table_name='hot_fix_records')
    op.drop_table('hot_fix_records')
    op.drop_index('ix_deployments_user_id_status', table_name='deployments')
    op.drop_index('ix_deployments_user_id', table_name='deployments')
    op.drop_index('ix_deployments_project_id', table_name='deployments')
    op.drop_index('ix_deployments_build_id', table_name='deployments')
    op.drop_table('deployments')
    op.drop_index('ix_coherence_reports_build_id', table_name='coherence_reports')
    op.drop_table('coherence_reports')
    op.drop_index('ix_chat_messages_user_id_status', table_name='chat_messages')
    op.drop_index('ix_chat_messages_user_id', table_name='chat_messages')
    op.drop_index('ix_chat_messages_session_id', table_name='chat_messages')
    op.drop_index('ix_chat_messages_project_id', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ix_build_snapshots_project_id', table_name='build_snapshots')
    op.drop_index('ix_build_snapshots_build_id', table_name='build_snapshots')
    op.drop_table('build_snapshots')
    op.drop_index('ix_annotations_user_id_status', table_name='annotations')
    op.drop_index('ix_annotations_user_id', table_name='annotations')
    op.drop_index('ix_annotations_project_id', table_name='annotations')
    op.drop_index('ix_annotations_editor_session_id', table_name='annotations')
    op.drop_table('annotations')
    op.drop_index('ix_accessibility_reports_build_id', table_name='accessibility_reports')
    op.drop_table('accessibility_reports')
    op.drop_index('ix_preview_shares_user_id_status', table_name='preview_shares')
    op.drop_index('ix_preview_shares_user_id', table_name='preview_shares')
    op.drop_index('ix_preview_shares_sandbox_id', table_name='preview_shares')
    op.drop_table('preview_shares')
    op.drop_index('ix_editor_sessions_user_id_status', table_name='editor_sessions')
    op.drop_index('ix_editor_sessions_user_id', table_name='editor_sessions')
    op.drop_index('ix_editor_sessions_sandbox_id', table_name='editor_sessions')
    op.drop_index('ix_editor_sessions_project_id', table_name='editor_sessions')
    op.drop_table('editor_sessions')
    op.drop_index('ix_builds_user_id_status', table_name='builds')
    op.drop_index('ix_builds_user_id', table_name='builds')
    op.drop_index('ix_builds_project_id_status', table_name='builds')
    op.drop_index('ix_builds_project_id', table_name='builds')
    op.drop_index('ix_builds_pipeline_run_id', table_name='builds')
    op.drop_table('builds')
    op.drop_index('ix_agent_outputs_pipeline_run_id', table_name='agent_outputs')
    op.drop_table('agent_outputs')
    op.drop_index('ix_sandboxes_status', table_name='sandboxes')
    op.drop_index('ix_sandboxes_project_id', table_name='sandboxes')
    op.drop_table('sandboxes')
    op.drop_index('ix_pipeline_runs_user_id_status', table_name='pipeline_runs')
    op.drop_index('ix_pipeline_runs_user_id', table_name='pipeline_runs')
    op.drop_index('ix_pipeline_runs_project_id', table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index('ix_ideas_user_id_status', table_name='ideas')
    op.drop_index('ix_ideas_user_id', table_name='ideas')
    op.drop_index('ix_ideas_idea_session_id', table_name='ideas')
    op.drop_table('ideas')
    op.drop_index('ix_projects_user_id_status_updated', table_name='projects')
    op.drop_index('ix_projects_user_id_status', table_name='projects')
    op.drop_index('ix_projects_user_id', table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_idea_sessions_user_id_status', table_name='idea_sessions')
    op.drop_index('ix_idea_sessions_user_id', table_name='idea_sessions')
    op.drop_table('idea_sessions')
    op.drop_index('uq_ai_providers_user_provider', table_name='ai_providers')
    op.drop_index('ix_ai_providers_user_id_status', table_name='ai_providers')
    op.drop_index('ix_ai_providers_user_id', table_name='ai_providers')
    op.drop_table('ai_providers')
    op.drop_table('users')
    # ### end Alembic commands ###
